name: scala-steward
on:
  push:
  schedule:
  - cron: '0 0 * * *'
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
    - uses: olafurpg/setup-scala@v10
    - uses: laughedelic/coursier-setup@v1
    - uses: coursier/cache-action@v5
    - uses: xuwei-k/scala-steward-latest@c7e7821a1295d06706005accaae131e30c99e94e
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
